[project]
name = "kpi-copilot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pam Manyika", email = "pam.manyika@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=2.1.0",
]

[project.scripts]
kpi-copilot = "kpi_copilot:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
